export { default as Facebook } from "./Facebook";
export { default as Gift } from "./Gift";
export { default as Instagram } from "./Instagram";
export { default as Linkedin } from "./Linkedin";
export { default as Survey } from "./Survey";
export { default as Threads } from "./Threads";
export { default as Twitter } from "./Twitter";
export { default as Whatsapp } from "./Whatsapp";
export { default as Youtube } from "./Youtube";
